import { test } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { computeInstallPath, classifyExisting, planInstall } from '../install-skills.mjs';
import { renderAdapter } from '../render-adapters.mjs';

test('computeInstallPath for claude-code user scope uses a stable home-relative path, not a project checkout path', () => {
  const p = computeInstallPath({ platform: 'claude-code', scope: 'user', skillId: 'ush-example-skill', homeDir: 'C:\\Users\\admin' });
  assert.equal(p, path.join('C:\\Users\\admin', '.claude', 'skills', 'ush-example-skill', 'SKILL.md'));
});

test('computeInstallPath for claude-code project scope is relative to the given project root', () => {
  const p = computeInstallPath({ platform: 'claude-code', scope: 'project', skillId: 'ush-example-skill', projectRoot: 'D:\\some\\project' });
  assert.equal(p, path.join('D:\\some\\project', '.claude', 'skills', 'ush-example-skill', 'SKILL.md'));
});

test('computeInstallPath refuses to embed a caller-supplied project checkout path into a user-scope install', () => {
  assert.throws(() => {
    computeInstallPath({ platform: 'claude-code', scope: 'user', skillId: 'ush-example-skill', homeDir: 'C:\\Users\\admin', projectRoot: 'D:\\some\\project' });
  }, /project/i);
});

// classifyExisting ownership detection uses the actual GENERATED marker
// render-adapters.mjs embeds (skill id + platform + content hash), not a
// bare substring match on the word "GENERATED" — see renderAdapter's marker
// format in scripts/render-adapters.mjs.
const RENDER_ARGS = {
  skillId: 'ush-example-skill',
  canonicalBody: 'canonical body\n',
  platform: 'claude-code',
  capabilities: { requires: [] },
  sourceCommit: 'abc123',
};
const expectedContent = renderAdapter(RENDER_ARGS).content;

test('classifyExisting: no existing file is "not_installed"', () => {
  const result = classifyExisting({ existingContent: null, expectedContent, skillId: RENDER_ARGS.skillId, platform: RENDER_ARGS.platform });
  assert.equal(result, 'not_installed');
});

test('classifyExisting: an unmanaged file that merely contains the ordinary word "GENERATED" is still "unmanaged" (regression: must not be treated as ours)', () => {
  const result = classifyExisting({
    existingContent: 'This file was auto-GENERATED by some other unrelated tool and hand-edited since.',
    expectedContent,
    skillId: RENDER_ARGS.skillId,
    platform: RENDER_ARGS.platform,
  });
  assert.equal(result, 'unmanaged');
});

test('classifyExisting: existing file matches the expected render exactly -> "managed_current"', () => {
  const result = classifyExisting({ existingContent: expectedContent, expectedContent, skillId: RENDER_ARGS.skillId, platform: RENDER_ARGS.platform });
  assert.equal(result, 'managed_current');
});

test('classifyExisting: a valid marker for THIS skill/platform but stale content -> "managed_stale" (update allowed)', () => {
  const staleRender = renderAdapter({ ...RENDER_ARGS, canonicalBody: 'an older canonical body\n' });
  const result = classifyExisting({ existingContent: staleRender.content, expectedContent, skillId: RENDER_ARGS.skillId, platform: RENDER_ARGS.platform });
  assert.equal(result, 'managed_stale');
});

test('classifyExisting: a marker present but for a DIFFERENT skill id -> "unmanaged" (never claim ownership of another skill\'s file)', () => {
  const otherSkillRender = renderAdapter({ ...RENDER_ARGS, skillId: 'ush-someone-elses-skill' });
  const result = classifyExisting({ existingContent: otherSkillRender.content, expectedContent, skillId: RENDER_ARGS.skillId, platform: RENDER_ARGS.platform });
  assert.equal(result, 'unmanaged');
});

test('classifyExisting: a marker present but for a DIFFERENT platform -> "unmanaged"', () => {
  const otherPlatformRender = renderAdapter({ ...RENDER_ARGS, platform: 'codex' });
  const result = classifyExisting({ existingContent: otherPlatformRender.content, expectedContent, skillId: RENDER_ARGS.skillId, platform: RENDER_ARGS.platform });
  assert.equal(result, 'unmanaged');
});

test('planInstall in dry-run mode (the default) never writes and reports the action it would take', () => {
  const plan = planInstall({
    skillId: 'ush-example-skill',
    platform: 'claude-code',
    scope: 'user',
    canonicalBody: 'body',
    render: () => ({ blocked: false, content: renderAdapter({ ...RENDER_ARGS, canonicalBody: 'body' }).content }),
    homeDir: 'C:\\Users\\admin',
    existingContent: null,
    apply: false,
  });
  assert.equal(plan.wouldWrite, true);
  assert.equal(plan.wrote, false);
  assert.equal(plan.classification, 'not_installed');
});

test('planInstall never overwrites an "unmanaged" existing file (ordinary hand-written content), even with apply:true', () => {
  const plan = planInstall({
    skillId: 'ush-example-skill',
    platform: 'claude-code',
    scope: 'user',
    canonicalBody: 'body',
    render: () => ({ blocked: false, content: renderAdapter({ ...RENDER_ARGS, canonicalBody: 'body' }).content }),
    homeDir: 'C:\\Users\\admin',
    existingContent: 'a file the user wrote by hand',
    apply: true,
  });
  assert.equal(plan.classification, 'unmanaged');
  assert.equal(plan.wouldWrite, false);
  assert.equal(plan.wrote, false);
  assert.ok(plan.reason.toLowerCase().includes('unmanaged'));
});

test('planInstall never overwrites a file merely containing the word "GENERATED" that this installer did not create, even with apply:true (regression)', () => {
  const plan = planInstall({
    skillId: 'ush-example-skill',
    platform: 'claude-code',
    scope: 'user',
    canonicalBody: 'body',
    render: () => ({ blocked: false, content: renderAdapter({ ...RENDER_ARGS, canonicalBody: 'body' }).content }),
    homeDir: 'C:\\Users\\admin',
    existingContent: 'auto-GENERATED by a different tool entirely, then hand-edited',
    apply: true,
  });
  assert.equal(plan.classification, 'unmanaged');
  assert.equal(plan.wrote, false);
});
